### ISSUE TITLE
descriptions for packages

### ISSUE THREAD

**Issue by liljaylj** [fish-shell/wahoo#57] opened 2015-07-21 17:34 UTC
it will be nice to know what package is about before/after install. i mean something like `pip search <query-string>`.
for example:
```
> wa search ansimble
ansimble             - Ansible development package for Wahoo
```

**Comment by bucaran** [comment] 2015-07-22 01:33
Sounds fair. This would require modifying the database to add the descriptions, which will of course have side effects :stuck_out_tongue_winking_eye: 

Let me see what I can come up with in the next following days.

**Comment by s0r00t** [comment] 2015-07-22 16:15
Isn't this a duplicate of #26 ?

**Comment by bucaran** [comment] 2015-07-22 16:55
Yes, it seems so.

**Closed** 2015-07-22 16:56 UTC
Labels: feature
